matrix:
  include:
  - os: osx
    env: COMPILER='clang++'
    osx_image: xcode8.2
  - os: osx
    env: COMPILER='clang++'
    osx_image: xcode8

install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update ; brew uninstall --force cmake; brew install cmake ; fi
  - git submodule update --init --recursive

before_script:
  - export CXX=$COMPILER
  - cd test
  - mkdir darwin && cd darwin

script:
  - cmake .. -DTRAVIS=ON -DEXTRA_TESTS=ON
  - make VERBOSE=1 && ./unittests --pass
